#############################################################################
# Makefile for building: gui.app/Contents/MacOS/gui
# Generated by qmake (3.1) (Qt 6.9.1)
# Project:  gui.pro
# Template: app
# Command: /usr/local/Qt-6.9.1/bin/qmake6 -o gui.xcodeproj/project.pbxproj gui.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

MOC       = /usr/local/Qt-6.9.1/libexec/moc
UIC       = 
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DMACXDEP -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
INCPATH       = -I. -I. -I../kiax2core -I../kiax2core/includes -I../kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -F/usr/local/Qt-6.9.1/lib
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compilers: moc_predefs.h moc_Kiax2MainWindow.cpp moc_Kiax2AboutDialog.cpp moc_Kiax2AccountDialog.cpp\
	 moc_Kiax2CallDialog.cpp moc_Kiax2ContactDialog.cpp moc_Kiax2ContactListItemWidget.cpp\
	 moc_Kiax2SettingsDialog.cpp moc_IAX2CallbackHandlerQt.cpp moc_Kiax2ConnectionMeter.cpp\
	 moc_Kiax2JSONBalance.cpp moc_Kiax2LoginScreen.cpp moc_Kiax2Application.cpp\
	 moc_Kiax2JSONUsersOnline.cpp moc_kiax2JSONNotification.cpp moc_Kiax2JSONServers.cpp\
	 moc_Kiax2DispatcherServer.cpp moc_Kiax2DispatcherThread.cpp moc_Kiax2JSONSupernode.cpp\
	 moc_Kiax2CallAppearance.cpp moc_Kiax2CallDialogView.cpp moc_Kiax2CallButton.cpp
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/Qt-6.9.1/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++1z -fPIC -dM -E -o moc_predefs.h /usr/local/Qt-6.9.1/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_Kiax2MainWindow.cpp moc_Kiax2AboutDialog.cpp moc_Kiax2AccountDialog.cpp moc_Kiax2CallDialog.cpp moc_Kiax2ContactDialog.cpp moc_Kiax2ContactListItemWidget.cpp moc_Kiax2SettingsDialog.cpp moc_IAX2CallbackHandlerQt.cpp moc_Kiax2ConnectionMeter.cpp moc_Kiax2JSONBalance.cpp moc_Kiax2LoginScreen.cpp moc_Kiax2Application.cpp moc_Kiax2JSONUsersOnline.cpp moc_kiax2JSONNotification.cpp moc_Kiax2JSONServers.cpp moc_Kiax2DispatcherServer.cpp moc_Kiax2DispatcherThread.cpp moc_Kiax2JSONSupernode.cpp moc_Kiax2CallAppearance.cpp moc_Kiax2CallDialogView.cpp moc_Kiax2CallButton.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Kiax2MainWindow.cpp moc_Kiax2AboutDialog.cpp moc_Kiax2AccountDialog.cpp moc_Kiax2CallDialog.cpp moc_Kiax2ContactDialog.cpp moc_Kiax2ContactListItemWidget.cpp moc_Kiax2SettingsDialog.cpp moc_IAX2CallbackHandlerQt.cpp moc_Kiax2ConnectionMeter.cpp moc_Kiax2JSONBalance.cpp moc_Kiax2LoginScreen.cpp moc_Kiax2Application.cpp moc_Kiax2JSONUsersOnline.cpp moc_kiax2JSONNotification.cpp moc_Kiax2JSONServers.cpp moc_Kiax2DispatcherServer.cpp moc_Kiax2DispatcherThread.cpp moc_Kiax2JSONSupernode.cpp moc_Kiax2CallAppearance.cpp moc_Kiax2CallDialogView.cpp moc_Kiax2CallButton.cpp
moc_Kiax2MainWindow.cpp: Kiax2MainWindow.h \
		../kiax2core/includes/iaxclient.h \
		/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers/QtGui \
		../kiax2core/Core.h \
		../kiax2core/APIBinderDefault.h \
		ui_kiax2windowAlt.h \
		Kiax2AboutDialog.h \
		ui_aboutdialog.h \
		Kiax2ContactDialog.h \
		ui_contactdialog.h \
		Kiax2AccountDialog.h \
		ui_accountdialog.h \
		../kiax2core/PConstants.h \
		../kiax2core/PConfiguration.h \
		/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers/QDesktopServices \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QUrl \
		Kiax2RegisterDialog.h \
		Kiax2ChangePassDialog.h \
		Kiax2CallDialog.h \
		ui_calldialog.h \
		../kiax2core/APIBinder.h \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QDateTime \
		Kiax2CallAppearance.h \
		Kiax2ListWidgetItem.h \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QString \
		../kiax2core/Logger.h \
		Kiax2SettingsDialog.h \
		ui_settingsdialog.h \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QStringList \
		Kiax2ContactListItemWidget.h \
		ui_contactlistitemwidget.h \
		Kiax2ConnectionMeter.h \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QtNetwork \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QFile \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkRequest \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkReply \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QThread \
		Kiax2JSONBalance.h \
		../kiax2core/tinyxml/tinyxml.h \
		Kiax2JSONUsersOnline.h \
		IAX2CallbackHandlerQt.h \
		../kiax2core/IAX2CallbackHandler.h \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QUrlQuery \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QTranslator \
		Kiax2LoginScreen.h \
		ui_loginscreen.h \
		Kiax2Application.h \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QEvent \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QSharedMemory \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QLocalServer \
		Kiax2JSONNotification.h \
		Kiax2DispatcherServer.h \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QTcpServer \
		Kiax2DispatcherThread.h \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QTcpSocket \
		Kiax2JSONSupernode.h \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QList \
		../kiax2core/Account.h \
		Kiax2JSONServers.h \
		Kiax2Servers.h \
		../kiax2core/Configuration.h \
		Kiax2CallButton.h \
		Kiax2DotTelDialog.h \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib Kiax2MainWindow.h -o moc_Kiax2MainWindow.cpp

moc_Kiax2AboutDialog.cpp: Kiax2AboutDialog.h \
		ui_aboutdialog.h \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib Kiax2AboutDialog.h -o moc_Kiax2AboutDialog.cpp

moc_Kiax2AccountDialog.cpp: Kiax2AccountDialog.h \
		ui_accountdialog.h \
		../kiax2core/PConstants.h \
		../kiax2core/PConfiguration.h \
		/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers/QDesktopServices \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QUrl \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib Kiax2AccountDialog.h -o moc_Kiax2AccountDialog.cpp

moc_Kiax2CallDialog.cpp: Kiax2CallDialog.h \
		ui_calldialog.h \
		../kiax2core/APIBinder.h \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QDateTime \
		Kiax2CallAppearance.h \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib Kiax2CallDialog.h -o moc_Kiax2CallDialog.cpp

moc_Kiax2ContactDialog.cpp: Kiax2ContactDialog.h \
		ui_contactdialog.h \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib Kiax2ContactDialog.h -o moc_Kiax2ContactDialog.cpp

moc_Kiax2ContactListItemWidget.cpp: Kiax2ContactListItemWidget.h \
		ui_contactlistitemwidget.h \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib Kiax2ContactListItemWidget.h -o moc_Kiax2ContactListItemWidget.cpp

moc_Kiax2SettingsDialog.cpp: Kiax2SettingsDialog.h \
		ui_settingsdialog.h \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QString \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QStringList \
		../kiax2core/PConstants.h \
		../kiax2core/PConfiguration.h \
		../kiax2core/includes/iaxclient.h \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib Kiax2SettingsDialog.h -o moc_Kiax2SettingsDialog.cpp

moc_IAX2CallbackHandlerQt.cpp: IAX2CallbackHandlerQt.h \
		../kiax2core/IAX2CallbackHandler.h \
		../kiax2core/Logger.h \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers/qevent.h \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib IAX2CallbackHandlerQt.h -o moc_IAX2CallbackHandlerQt.cpp

moc_Kiax2ConnectionMeter.cpp: Kiax2ConnectionMeter.h \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QtNetwork \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QFile \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkRequest \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkReply \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QUrl \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QDebug \
		../kiax2core/Logger.h \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QDateTime \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QThread \
		../kiax2core/PConfiguration.h \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib Kiax2ConnectionMeter.h -o moc_Kiax2ConnectionMeter.cpp

moc_Kiax2JSONBalance.cpp: Kiax2JSONBalance.h \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QtNetwork \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkRequest \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkReply \
		../kiax2core/Logger.h \
		../kiax2core/PConfiguration.h \
		../kiax2core/tinyxml/tinyxml.h \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib Kiax2JSONBalance.h -o moc_Kiax2JSONBalance.cpp

moc_Kiax2LoginScreen.cpp: Kiax2LoginScreen.h \
		ui_loginscreen.h \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib Kiax2LoginScreen.h -o moc_Kiax2LoginScreen.cpp

moc_Kiax2Application.cpp: Kiax2Application.h \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QEvent \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QSharedMemory \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QLocalServer \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib Kiax2Application.h -o moc_Kiax2Application.cpp

moc_Kiax2JSONUsersOnline.cpp: Kiax2JSONUsersOnline.h \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QtNetwork \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkRequest \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkReply \
		../kiax2core/Logger.h \
		../kiax2core/PConfiguration.h \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib Kiax2JSONUsersOnline.h -o moc_Kiax2JSONUsersOnline.cpp

moc_kiax2JSONNotification.cpp: kiax2JSONNotification.h \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QtNetwork \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		../kiax2core/Logger.h \
		../kiax2core/PConfiguration.h \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib kiax2JSONNotification.h -o moc_kiax2JSONNotification.cpp

moc_Kiax2JSONServers.cpp: Kiax2JSONServers.h \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QtNetwork \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkRequest \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkReply \
		../kiax2core/Logger.h \
		../kiax2core/PConfiguration.h \
		Kiax2Servers.h \
		../kiax2core/Configuration.h \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib Kiax2JSONServers.h -o moc_Kiax2JSONServers.cpp

moc_Kiax2DispatcherServer.cpp: Kiax2DispatcherServer.h \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QTcpServer \
		Kiax2DispatcherThread.h \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QTcpSocket \
		Kiax2DispatcherServer.h \
		../kiax2core/Account.h \
		Kiax2JSONSupernode.h \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QtNetwork \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkRequest \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkReply \
		../kiax2core/Logger.h \
		../kiax2core/PConfiguration.h \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QList \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib Kiax2DispatcherServer.h -o moc_Kiax2DispatcherServer.cpp

moc_Kiax2DispatcherThread.cpp: Kiax2DispatcherThread.h \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QTcpSocket \
		Kiax2DispatcherServer.h \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QTcpServer \
		Kiax2DispatcherThread.h \
		Kiax2JSONSupernode.h \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QtNetwork \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkRequest \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkReply \
		../kiax2core/Logger.h \
		../kiax2core/PConfiguration.h \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QList \
		../kiax2core/Account.h \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib Kiax2DispatcherThread.h -o moc_Kiax2DispatcherThread.cpp

moc_Kiax2JSONSupernode.cpp: Kiax2JSONSupernode.h \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QtNetwork \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkRequest \
		/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers/QNetworkReply \
		../kiax2core/Logger.h \
		../kiax2core/PConfiguration.h \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib Kiax2JSONSupernode.h -o moc_Kiax2JSONSupernode.cpp

moc_Kiax2CallAppearance.cpp: Kiax2CallAppearance.h \
		../kiax2core/APIBinder.h \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QDateTime \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib Kiax2CallAppearance.h -o moc_Kiax2CallAppearance.cpp

moc_Kiax2CallDialogView.cpp: Kiax2CallDialogView.h \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QEvent \
		/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers/QCloseEvent \
		/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers/QShowEvent \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib Kiax2CallDialogView.h -o moc_Kiax2CallDialogView.cpp

moc_Kiax2CallButton.cpp: Kiax2CallButton.h \
		ui_calldialog.h \
		../kiax2core/APIBinder.h \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers/QDateTime \
		Kiax2CallAppearance.h \
		moc_predefs.h \
		/usr/local/Qt-6.9.1/libexec/moc
	/usr/local/Qt-6.9.1/libexec/moc $(DEFINES) --include /Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui/moc_predefs.h -I/usr/local/Qt-6.9.1/mkspecs/macx-clang -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/gui -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes -I/Users/ballcam/Source/TalkFone/macOS-15.6/kiax-code/kiax2core/includes/json -I/usr/local/Qt-6.9.1/lib/QtGui.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtNetwork.framework/Headers -I/usr/local/Qt-6.9.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.5.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/usr/local/Qt-6.9.1/lib Kiax2CallButton.h -o moc_Kiax2CallButton.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

